//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentist
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbPatient
    {
        public string PatientName { get; set; }
        public Nullable<int> PatientAge { get; set; }
        public Nullable<decimal> PaidUp { get; set; }
        public Nullable<decimal> TheRest { get; set; }
        public string PatientPhone { get; set; }
        public string Done { get; set; }
        public Nullable<System.DateTime> ExaminationTime { get; set; }
        public Nullable<System.DateTime> ReExaminationTime { get; set; }
    }
}
